### ISSUE TITLE
Corrigir instalação do Docker 

### ISSUE THREAD

**Issue by marcopollivier** [marcopollivier/big-bang#1]
Docker não está instalando corretamente 

Issue exclusiva para Ubuntu

**Comment by Hixian** [comment]
Dá uma olhada nesse script, e veja se resolve. Aproveita e usa o loop **with_items** para diminuir a quantidade de código na hora de instalar pacotes:

https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933

**Comment by marcopollivier** [comment]
@Hixian Ontem eu escrevi um muito parecido, mas tinha ficado um pouco mais verboso e o artefato do Docker que eu tava usando não tava sendo encontrado. Fiquei de corrigir, mas não tive tempo. De qualquer forma gostei da forma que esse foi estruturado. Vou me basear nele em algumas paradas. Valeu =D

**Comment by marcopollivier** [comment]
correcao feita para ambiente manjaro
